version: "3.7"

services: 
  path_empathy_database:
    image: postgres
    container_name: path_empathy_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=path_empathy
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: pathapi
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app 
    links:
      - path_empathy_database
    depends_on: 
      - path_empathy_database

volumes:
  pgdata:
    driver: local