version: "3.7"

networks:
  compose_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24

services: 
  postgres:
    image: postgres
    container_name: path_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=path_empathy
    volumes:
      - pgdata:/data/postgres
    networks:
      compose_net:
        ipv4_address: 172.20.0.5
  redis:
    container_name: path_redis
    image: redis:alpine
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
    links:
      - path_database
    networks:
      compose_net:
        ipv4_address: 172.20.0.6
  app: 
    build: .
    container_name: pathapi
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - path_database
      - path_redis
    depends_on: 
      - path_database
      - path_redis
    networks:
      compose_net:
        ipv4_address: 172.20.0.7
volumes:
  pgdata:
    driver: local